### ISSUE TITLE
[One Dark] missing some punctuation.* scopes

### ISSUE THREAD

**Issue by rwols** [AmjadHD/sublime_one_theme#2] opened 2021-01-23 21:01 UTC
For the One Dark color scheme I'm missing punctuation scopes:

- `punctuation.definition.variable`
- `punctuation.section`

In the screenshot below you can see that the `$`, `{` and `}` characters are somewhat boring. But they do have accurate scopes assigned to them:

```
option(${PROJECT_UPPER}_BUILD_TESTS "Build unit tests" ON)
#      ^ punctuation.definition.variable
#       ^ punctuation.section
#                     ^ punctuation.section
```

<img width="895" alt="image" src="https://user-images.githubusercontent.com/2431823/105613974-33450080-5dc6-11eb-8df8-3e504ecfac84.png">

**Comment by AmjadHD** [comment] 2021-01-23 21:05
I'm not sure what color should assign to them, an operator's, an interpolation's, a separate color ?

**Comment by AmjadHD** [comment] 2021-01-23 21:06
What is this syntax ? make ?

**Comment by rwols** [comment] 2021-01-23 21:33
It's CMake but it doesn't matter much which syntax this is. The same issue can be seen for Bash. For instance take a look at this file in ST (set the syntax to Bash): https://git.kernel.org/pub/scm/git/git.git/plain/git-gui/git-gui.sh

You may also want to add a color to `variable.other`. So:

- `punctuation.definition.variable`
- `punctuation.section`
- `variable.other`

**Comment by AmjadHD** [comment] 2021-01-23 23:03
can you paste the snippet in the screenshot, `{` and `}` in `${name}` are colored for me they have the scope `punctuation.section.interpolation`.

**Comment by rwols** [comment] 2021-01-23 23:06
> can you paste the snippet in the screenshot

```
option(${PROJECT_UPPER}_BUILD_TESTS "Build unit tests" ON)
option(${PROJECT_UPPER}_BUILD_EDITOR "Build the editor" ON)
option(${PROJECT_UPPER}_BUILD_VIEWER "Build the glTF viewer" ON)
option(${PROJECT_UPPER}_COVERAGE "Build with coverage instrumentation enabled" OFF)
option(${PROJECT_UPPER}_CLANG_TIDY "Build with clang-tidy checks enabled" OFF)
option(${PROJECT_UPPER}_MOBILE "Build for mobile devices" OFF)
option(${PROJECT_UPPER}_SIMD_BASELINE_SSE_3 "Regard sse3 as minimum required instruction set" OFF)
option(${PROJECT_UPPER}_SIMD_BASELINE_SSE_4_1 "Regard sse4.1 as minimum required instruction set" ON)
option(${PROJECT_UPPER}_ADDRESS_SANITIZER "Use the address sanitizer" OFF)
option(${PROJECT_UPPER}_THREAD_SANITIZER "Use the thread sanitizer" OFF)

cmake_dependent_option(${PROJECT_UPPER}_LINUX "Use the linux display backend" ON "UNIX;NOT APPLE" OFF)
cmake_dependent_option(${PROJECT_UPPER}_WIN32 "Use the win32 display backend" ON "WIN32" OFF)
cmake_dependent_option(${PROJECT_UPPER}_MACOS "Use the macOS display backend" ON "APPLE;NOT ${PROJECT_UPPER}_MOBILE" OFF)
cmake_dependent_option(${PROJECT_UPPER}_IOS "Use the iOS display backend" ON "APPLE;${PROJECT_UPPER}_MOBILE" OFF)
```

> { and } in ${name} are colored for me they have the scope punctuation.section.interpolation

I'm fairly certain variables have the scope `variable.other`.

<img width="895" alt="image" src="https://user-images.githubusercontent.com/2431823/105616508-e10cdb00-5dd7-11eb-954f-e31fd15b4a2e.png">

**Comment by AmjadHD** [comment] 2021-01-23 23:13
I mean `{` and `}`.

**Comment by rwols** [comment] 2021-01-23 23:25
Apologies, I see what you mean now. Yes we have coloring for punctuation.section.interpolation but my issue still stands.

**Comment by AmjadHD** [comment] 2021-01-23 23:47
Does this look good
![image](https://user-images.githubusercontent.com/33235928/105617168-ca698280-5ddd-11eb-8299-72fd60921760.png)

**Comment by rwols** [comment] 2021-01-24 13:08
Looks like an improvement. Perhaps `variable.other` is a bit too red for my taste :) but I'll let you be the judge of that.

**Comment by AmjadHD** [comment] 2021-01-24 14:25
I try to follow the original theme.
this is how it looks in atom:
![image](https://user-images.githubusercontent.com/33235928/105633295-10fbc300-5e58-11eb-92ac-b80dcede959d.png)
The problem is the usage of `variable.other` in atom and sublime text differs in many cases, which makes kind of annoying to follow the original theme.
for example after changes, I get different highlighting for javascript:
Atom:
![atom](https://user-images.githubusercontent.com/33235928/105633473-11e12480-5e59-11eb-8d94-97ccdd643ff9.png)
Sublime Text:
![sublime_text](https://user-images.githubusercontent.com/33235928/105633478-19a0c900-5e59-11eb-852d-bbb76f37985e.png)

**Comment by AmjadHD** [comment] 2021-01-25 22:21
After thinking about, i don't think I will add a color to `variable.other`, all default (and most third party) color schemes don't. many syntaxes will become a mess, and personally I'm not a fan of highlighting variables. I did add color to `puntuation.definition.variable`. Feel free to customize the color scheme if you wish (there's a `customize color scheme` command in ST4095).

**Closed as completed** 2021-01-26 22:34 UTC
Labels: wontfix
